n=str(input('introduceti primul cuvant'))
m=str(input('introduceti al doilea cuvant'))
p=str(input('introduceti al treilea cuvant'))
l=str(input('introduceti al patrulea cuvant'))
print(n)
print(m)
print(p)
print(l)
print(n,'',m,'',p,'',l,'.')