nume = str(input("Cum te numesti?\n"))
virsta = str(input("Cati ani ai?\n"))
institutia = str(input("In ce institutie inveti?\n"))
hobby = str(input("Care este hobbyul ?\n"))
print(f'Te numesti {nume}, ai {virsta} ani, inveti in {institutia} si hobbyul tau este {hobby}, iti doresc mult succes in continuare')